/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/rolodexV3.2.glb 
*/

import React, { Ref, useImperativeHandle, useState } from 'react'
import { useGLTF, useAnimations, Center } from '@react-three/drei'
import * as THREE from "three";

export interface RolodexRef {
  triggerAnim: () => void
}

type GLTFResult = {
  nodes: {
    [name: string]: THREE.Mesh
  },
  materials: {
    [name: string]: THREE.Material
  },
  animations: THREE.AnimationClip[]
}

export default function Rolodex({ ref }: { ref: Ref<RolodexRef> } ) {
  const group = React.useRef(null)
  const { nodes, materials, animations } = useGLTF('/rolodexV3.2.glb') as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  const [isPlaying, setIsPlaying] = useState<boolean>(false)

  const animateRolodex = () => {
    if (isPlaying) return
    setIsPlaying(true)
    Object.values(actions).forEach((action) => {
      if (action) {
        action.reset();
        action.setLoop(THREE.LoopOnce, 1);
        action.timeScale = 1;
        action.play();
      }
    });
    setTimeout(() => {
      setIsPlaying(false)
    }, 1000)
  }

  useImperativeHandle(ref, () => ({
    triggerAnim: animateRolodex
  }))

  return (
    <Center top left>
      <group ref={group} dispose={null}>
        <group name="Scene">
          <group name="Vert006" position={[0.435, 0, 0.665]} scale={1.257}>
            <mesh name="Vert007" geometry={nodes.Vert007.geometry} material={materials['Material.004']} />
            <mesh name="Vert007_1" geometry={nodes.Vert007_1.geometry} material={materials['Outline.004']} />
          </group>
          <group name="Static_cards" position={[0, 3.303, -0.334]} rotation={[Math.PI, 0, Math.PI]} scale={[-1.4, -1, -1]}>
            <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials['Material.002']} />
            <mesh name="Plane009_1" geometry={nodes.Plane009_1.geometry} material={materials['Outline.002']} />
          </group>
          <group name="Lead_card" position={[-1.425, 4.372, -0.595]} rotation={[Math.PI, 0, Math.PI]} scale={[-1.4, -1, -1]}>
            <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials['Material.002']} />
            <mesh name="Plane013_1" geometry={nodes.Plane013_1.geometry} material={materials['Outline.002']} />
          </group>
          <group name="Top_spawn" position={[-1.425, 4.372, -0.595]} rotation={[Math.PI, 0, Math.PI]} scale={[-1.4, -1, -1]}>
            <mesh name="Plane014" geometry={nodes.Plane014.geometry} material={materials['Material.001']} />
            <mesh name="Plane014_1" geometry={nodes.Plane014_1.geometry} material={materials['Outline.001']} />
          </group>
          <group name="Lead_card001" position={[-1.425, 4.381, -0.667]} rotation={[3.046, 0, Math.PI]} scale={[-1.4, -1, -1]}>
            <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={materials['Material.003']} />
            <mesh name="Plane015_1" geometry={nodes.Plane015_1.geometry} material={materials['Outline.003']} />
          </group>
          <group name="Lead_card002" position={[-1.425, 4.381, -1.09]} rotation={[-3.11, 0, -Math.PI]} scale={[-1.4, -1, -1]}>
            <mesh name="Plane016" geometry={nodes.Plane016.geometry} material={materials['Material.005']} />
            <mesh name="Plane016_1" geometry={nodes.Plane016_1.geometry} material={materials['Outline.005']} />
          </group>
          <group name="Lead_card003" position={[-1.425, 4.143, -1.386]} rotation={[0.603, 0, Math.PI]} scale={[-1.4, -1, -1]}>
            <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials['Material.006']} />
            <mesh name="Plane017_1" geometry={nodes.Plane017_1.geometry} material={materials['Outline.006']} />
          </group>
        </group>
      </group>
    </Center>
  )
}

useGLTF.preload('/rolodexV3.2.glb')
